language: python

sudo: required

services:
  - docker

before_install:
  - git clone --recurse-submodules git://github.com/patrick330602/fomf3dbd-test-infra .omero

script:
  - .omero/docker scripts
